cinema/cinema/Controllers/MoviesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using cinema.Data;
using cinema.Models;
using cinema.Repositories;
using Microsoft.AspNetCore.Authorization;

namespace cinema.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieRepository _movieRepository;

        public MoviesController(IMovieRepository movieRepository)
        {
            _movieRepository = movieRepository;
        }

        // GET: Movies
        public async Task<IActionResult> Index()
        {
            return View(await _movieRepository.ListOfAllMovies());
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _movieRepository.FindMovieById(id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: Movies/Create
        [Authorize(Roles = "Backoffice-medewerker")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description,Director,Cast,ReleaseYear,CountryOfOrigin,Length,Genre,Poster,Language,ThreeD")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                _movieRepository.Add(movie);
                _movieRepository.SaveMovie();
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _movieRepository.FindMovieById(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Name,Description,Director,Cast,ReleaseYear,CountryOfOrigin,Length,Genre,Poster,Language,ThreeD")] Movie movie)
        {
            if (id != movie.Name)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _movieRepository.UpdateMovie(movie);
                    _movieRepository.SaveMovie();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Name))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _movieRepository.FindMovieById(id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var movie = await _movieRepository.FindMovieById(id);
            _movieRepository.RemoveMovie(movie);
            _movieRepository.SaveMovie();
            return RedirectToAction(nameof(Index));
        }

        public bool MovieExists(string id)
        {
            return _movieRepository.MovieExists(id);
        }
    }
}

cinema/cinema/Controllers/ShowsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using cinema.Data;
using cinema.Models;
using cinema.Services;
using cinema.Filters;
using cinema.Repositories;

namespace cinema.Controllers
{
    public class ShowsController : Controller
    {
        private readonly IShowRepository _showRepository;
        private readonly IShowService _showService;

        public ShowsController(IShowRepository showRepository, IShowService service)
        {
            
            _showRepository = showRepository;
            _showService = service;
        }

        // GET: Shows
        public async Task<IActionResult> Index()
        {

            var showList = _showRepository.ListOfShowsPerDate();
            var showPerMoviePerDateDict = _showService.GetShowsPerMoviePerDay(showList);

            ShowsFilter filter = new ShowsFilter(showList);
            ViewData["ShowsFilter"] = filter;

            return View(showPerMoviePerDateDict);
        }

        // GET: Shows/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var show = await _showRepository.FindShowById(id);
            if (show == null)
            {
                return NotFound();
            }

            return View(show);
        }

        // GET: Shows/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Shows/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ThreeD,Room,StartTime,Break")] Show show)
        {
            if (ModelState.IsValid)
            {
                _showRepository.Add(show);
                _showRepository.SaveShow();
                return RedirectToAction(nameof(Index));
            }
            return View(show);
        }

        // GET: Shows/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var show = await _showRepository.FindShowByIdWithoutFirstOrDefault(id);
            if (show == null)
            {
                return NotFound();
            }
            return View(show);
        }

        // POST: Shows/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ThreeD,Room,StartTime,Break")] Show show)
        {
            if (id != show.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _showRepository.UpdateShow(show);
                    _showRepository.SaveShow();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShowExists(show.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(show);
        }

        // GET: Shows/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var show = await _showRepository.FindShowById(id);
            if (show == null)
            {
                return NotFound();
            }

            return View(show);
        }

        // POST: Shows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var show = await _showRepository.FindShowByIdWithoutFirstOrDefault(id);
            _showRepository.RemoveShow(show);
            _showRepository.SaveShow();
            return RedirectToAction(nameof(Index));
        }

        public bool ShowExists(int id)
        {
            return _showRepository.ShowExists(id);
        }

        //GET: Shows/Daily
        public IActionResult Daily()
        {
            return View(_showRepository.SortedListOfShowsThatStartToday());
        }

        [HttpGet, HttpPost, ActionName("Filter")]
        public IActionResult Filter()
        {
            List<Show> shows = _showRepository.ListOfMoviesThatStartSoon();
            ShowsFilter filter = new ShowsFilter(shows);      
            if(Request.Method == HttpMethod.Post.Method)
            {
                if(Request.Form["search"] != "")
                    filter.input = Request.Form["search"];
                if (Request.Form["len"] != "")
                    filter.maxlength = Convert.ToDouble(Request.Form["len"]);
                if (Request.Form["date"] != "")
                    filter.date = Convert.ToDateTime(Request.Form["date"]);
                if (Request.Form["threed"] != "")
                    if (Request.Form["threed"] == "on")
                        filter.threed = true;
                    else
                        filter.threed = false;
                foreach (string language in filter.languages.Keys)
                    if (Request.Form[language] == "on")
                        filter.languages[language] = true;
                    else
                        filter.languages[language] = false;
                foreach (string genre in filter.genres.Keys)
                    if (Request.Form[genre] == "on")
                        filter.genres[genre] = true;
                    else
                        filter.genres[genre] = false;
                foreach (string kijkwijzer in filter.kijkwijzers.Keys)
                    if (Request.Form[kijkwijzer] == "on")
                        filter.kijkwijzers[kijkwijzer] = true;
                    else
                        filter.kijkwijzers[kijkwijzer] = false;
            }
            shows = filter.Apply(shows);
            ViewData["ShowsFilter"] = filter;
            return View("Index", _showService.GetShowsPerMoviePerDay(shows));
        }
    }
}

cinema/cinema/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using cinema.Models;
using cinema.ViewModels;

namespace cinema.Controllers
{
    public class UsersController : Controller
    {

        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UsersController(UserManager<IdentityUser> userManager
            , SignInManager<IdentityUser> signInManager
            , RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("index", "home");
        }
        
        [AllowAnonymous]
        public IActionResult AccessDenied(string returnUrl)
        {
            return new ObjectResult("Foei " + User?.Identity?.Name + "! Daar mag jij niet komen!");
            // betere mogelijkheid:
            //    //return RedirectToAction(returnUrl);
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View("Users/Register");
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = new IdentityUser()
                {
                    UserName = model.Name,
                    Email = model.Email
                };

                IdentityResult result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    if (_signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                    {
                        return RedirectToAction("ListUsers", "Administration");
                    }
                    
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToAction("index", "home");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return View("Users/Register" ,model);
        }


        [HttpGet]
        public IActionResult Login()
        {
            return View("Users/Login");
        }



        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                Microsoft.AspNetCore.Identity.SignInResult result
                    = await _signInManager.PasswordSignInAsync(
                        model.Name,
                        model.Password,
                        isPersistent: false, // aka: remember me?
                        lockoutOnFailure: false);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }

                ModelState.AddModelError("", "Login failed.");
            }

            return View("Users/Login", model);
        }

    }
}

cinema/cinema/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "Not Found";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewBag.ErrorMessage</h1>

<a asp-action="index" asp-controller="Home">Return To home page</a>

cinema/cinema/Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> _signInManager;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - cinema</title>
    <link rel="stylesheet" href="~/lib/bootstrap/bootstrap.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    @await RenderSectionAsync("Styles", required: false)

</head>
<body>
<header class="mb-4">
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand logo" href="#">
                <img src="~/imagesStyling/logo-se.png" alt="logo" class="img-responsive"/>
            </a>
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">cinema</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Shows" asp-action="Index">Voorstellingen</a>
                    </li>
                    @if (_signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                               data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Manage
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item text-dark" asp-controller="Administration"
                                   asp-action="ListUsers">Users</a>
                                <a class="dropdown-item text-dark" asp-controller="Administration"
                                   asp-action="ListRoles">Roles</a>
                            </div>
                        </li>
                    }
                     @if (_signInManager.IsSignedIn(User) && User.IsInRole("Backoffice-medewerker"))
                     {
                         <li class="nav-item">
                             <a class="nav-link" asp-area="" asp-controller="Movies" asp-action="Create">Film toevoegen</a>
                         </li>
                     }
                </ul>
                     <ul class="navbar-nav ml-auto">
                                        @*@{ IsSignedIn(User) - Returns true if the principal has an identity with the application cookie identity }
                                        @{ User: is System.Security.ClaimsPrincipal of the current logged in user }*@
                                        
                                        @if (User?.Identity?.IsAuthenticated ?? false) {
                                            <li class="nav-item">
                                                <form method="post" asp-action="logout" asp-controller="Users">
                                                    <button type="submit">
                                                        logout @User.Identity.Name<!-- todo stap-11a: laat naam ingelogde gebruiker zien-->
                                                    </button>
                                                </form>
                                            </li>
                                        } else {
                                            <!--todo lesson 4-6: maak navigatie links aan om te registreren en (latere stap) in te loggen -->
                                            <li class="nav-item">
                                                <a class="nav-link" asp-controller="Users" asp-action="Register">Register</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link" asp-controller="Users" asp-action="Login">Login</a>
                                            </li>
                                        }
                     </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container mt-5">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
<div class="footer-containe mt-5">
    <div id="mapssubscribe" class="container-fluid">
        <div class="row justify-content-evenly align-items-start">
            <div class="col-4">
                <input type="text" id="txtSource" placeholder="Vanaf"/>
                <input type="button" value="Route" onclick="GetRoute()" class="btn btn-primary btn-lg"/>

                <div id="Dropdown">
                    <b>Ik kom: </b>
                    <select id="mode">
                        <option value="DRIVING">Met de auto</option>
                        <option value="WALKING">Lopend</option>
                        <option value="BICYCLING">Fietsend</option>
                        <option value="TRANSIT">Met de OV</option>
                    </select>
                </div>
                <hr/>
                <div id="dvDistance" style="font-weight:bold; text-align: center">
                </div>
                <div id="dvMap">
                </div>
                <div id="dvPanel">
                </div>
            </div>
            <div class="col-4">
                <div>
                    <h4>Aanmelden voor nieuwsbrief</h4>
                    <form method="post" asp-action="Create" asp-controller="Subscribers">
                        <input name="email" type="text" placeholder="Email adres">
                        <input type="submit" class="btn btn-primary btn-lg" value="Aanmelden">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<footer class="shadow footer text-muted bg-black py-4 fixed-bottom">
    <div class="container footer-container text-white d-flex justify-content-between">
        <div>
            &copy; 2022 - cinema - <a asp-page="/Privacy" class="text-decoration-none">privacy</a>
        </div>
        <div>
            <a class="social-media text-decoration-none" href="https://www.facebook.com/avans/">
                <img src="~/imagesStyling/fb-bw.png" alt="fb" class="img-responsive mx-2" style="max-width: 30px"/>
            </a>
            <a class="social-media text-decoration-none" href="https://www.instagram.com/avanshogeschool/?hl=en">
                <img src="~/imagesStyling/ig-bw.png" alt="ig" class="img-responsive mx-2" style="max-width: 30px"/>
            </a>
            <a class="social-media text-decoration-none" href="https://twitter.com/avanshogeschool?lang=en">
                <img src="~/imagesStyling/tw-bw.png" alt="tw" class="img-responsive mx-2" style="max-width: 30px"/>
            </a>
        </div>

    </div>
</footer>

<script src="~/lib/bootstrap/bootstrap.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCXagAu3PsqAZ2hW-1CA7HnMY0BjBF87GM&libraries=places">  
              </script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>